# Conda environment for Gammapy and SimBMVtool
#
# Install:    conda env create -f environment-dev.yml
# Update:     conda env update -f environment-dev.yml
# Activate:   conda activate SimBMVtool
# Deactivate: conda deactivate

name: SimBMVtool

channels:
  - conda-forge
  - sherpa

variables:
  PYTHONNOUSERSITE: "1"

dependencies:
  # core dependencies
  - python=3.11
  - pip
  - astropy
  - click
  - cython
  - numpy>1.20
  - pydantic>=2.5
  - pyyaml
  - regions>=0.5
  - matplotlib>=3.4
  - scipy!=1.10
  - iminuit>=2.8.0
  - extension-helpers
  # test dependencies
  - requests
  - tqdm
  # extra dependencies
  - healpy
  - ipython
  - jupyter
  - jupyterlab
  - naima
  - pandas
  - pip:
      - sherpa
      - pytest-sphinx
      - ray[default]>=2.9
      - PyGithub
      - pypandoc
      - seaborn
      - scikit-image
